#cloud-config
 users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHtwz7fDFC/fatcs2Z+5sRJgxP8z+dO+ZH2F+xWRMr6e vboxuser@ubuntu-diplom
